# Store the npm packages in .yarn/cache
enableGlobalCache: false

# Disable telemetry
enableTelemetry: false

packageExtensions:
  # vite-plugin-top-level-await wants to access rollup, 
  # but it hasn't declared a dependency upon it.
  # So we have to fix it ourselves.
  vite-plugin-top-level-await@*:
    dependencies:
      rollup: "*"